services:
  mlops:
    build: .
    ports:
      - "5001:5001"
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./mlruns:/app/mlruns
      - ./data:/app/data
      - ./reports:/app/reports
      - ./models:/app/models
